const destinations = [
  {
    id: "kyoto",
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    imageTone: "temples, gardens, seasonal food",
    averageDailyCost: 185,
    idealDays: 6,
    bestMonths: ["Mar", "Apr", "May", "Oct", "Nov"],
    climate: "temperate",
    tags: ["culture", "food", "history", "walkable", "romantic"],
    pace: "balanced",
    travelerTypes: ["couple", "solo", "family"],
    safety: 0.92,
    popularity: 0.89,
    coordinates: { lat: 35.0116, lng: 135.7681 }
  },
  {
    id: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    imageTone: "coastline, tiled streets, cafes",
    averageDailyCost: 150,
    idealDays: 5,
    bestMonths: ["Apr", "May", "Jun", "Sep", "Oct"],
    climate: "warm",
    tags: ["food", "nightlife", "culture", "beach", "walkable"],
    pace: "balanced",
    travelerTypes: ["couple", "solo", "friends"],
    safety: 0.86,
    popularity: 0.84,
    coordinates: { lat: 38.7223, lng: -9.1393 }
  },
  {
    id: "banff",
    name: "Banff",
    country: "Canada",
    region: "North America",
    imageTone: "mountains, lakes, alpine trails",
    averageDailyCost: 230,
    idealDays: 7,
    bestMonths: ["Jun", "Jul", "Aug", "Sep", "Dec", "Jan"],
    climate: "cold",
    tags: ["nature", "adventure", "photography", "hiking", "quiet"],
    pace: "active",
    travelerTypes: ["couple", "solo", "family", "friends"],
    safety: 0.91,
    popularity: 0.78,
    coordinates: { lat: 51.1784, lng: -115.5708 }
  },
  {
    id: "mexico-city",
    name: "Mexico City",
    country: "Mexico",
    region: "North America",
    imageTone: "museums, markets, architecture",
    averageDailyCost: 115,
    idealDays: 5,
    bestMonths: ["Feb", "Mar", "Apr", "Oct", "Nov"],
    climate: "mild",
    tags: ["food", "culture", "history", "nightlife", "art"],
    pace: "active",
    travelerTypes: ["couple", "solo", "friends"],
    safety: 0.68,
    popularity: 0.82,
    coordinates: { lat: 19.4326, lng: -99.1332 }
  },
  {
    id: "queenstown",
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    imageTone: "lakes, peaks, adventure sports",
    averageDailyCost: 245,
    idealDays: 6,
    bestMonths: ["Jan", "Feb", "Mar", "Dec"],
    climate: "cool",
    tags: ["adventure", "nature", "hiking", "photography", "romantic"],
    pace: "active",
    travelerTypes: ["couple", "solo", "friends"],
    safety: 0.94,
    popularity: 0.76,
    coordinates: { lat: -45.0312, lng: 168.6626 }
  },
  {
    id: "marrakesh",
    name: "Marrakesh",
    country: "Morocco",
    region: "Africa",
    imageTone: "souks, riads, desert day trips",
    averageDailyCost: 95,
    idealDays: 4,
    bestMonths: ["Mar", "Apr", "May", "Oct", "Nov"],
    climate: "hot",
    tags: ["culture", "food", "history", "shopping", "photography"],
    pace: "balanced",
    travelerTypes: ["couple", "solo", "friends"],
    safety: 0.71,
    popularity: 0.72,
    coordinates: { lat: 31.6295, lng: -7.9811 }
  },
  {
    id: "costa-rica",
    name: "Costa Rica",
    country: "Costa Rica",
    region: "Central America",
    imageTone: "rainforest, surf, wildlife",
    averageDailyCost: 165,
    idealDays: 8,
    bestMonths: ["Jan", "Feb", "Mar", "Apr", "Dec"],
    climate: "tropical",
    tags: ["nature", "beach", "adventure", "wildlife", "wellness"],
    pace: "balanced",
    travelerTypes: ["couple", "family", "friends"],
    safety: 0.78,
    popularity: 0.8,
    coordinates: { lat: 9.7489, lng: -83.7534 }
  },
  {
    id: "copenhagen",
    name: "Copenhagen",
    country: "Denmark",
    region: "Europe",
    imageTone: "harbor, design, cycling",
    averageDailyCost: 260,
    idealDays: 4,
    bestMonths: ["May", "Jun", "Jul", "Aug", "Sep"],
    climate: "cool",
    tags: ["design", "food", "culture", "walkable", "quiet"],
    pace: "relaxed",
    travelerTypes: ["couple", "solo", "family"],
    safety: 0.95,
    popularity: 0.74,
    coordinates: { lat: 55.6761, lng: 12.5683 }
  },
  {
    id: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    imageTone: "rice terraces, beaches, wellness",
    averageDailyCost: 120,
    idealDays: 9,
    bestMonths: ["May", "Jun", "Jul", "Aug", "Sep"],
    climate: "tropical",
    tags: ["beach", "wellness", "food", "culture", "nature"],
    pace: "relaxed",
    travelerTypes: ["couple", "solo", "friends"],
    safety: 0.74,
    popularity: 0.88,
    coordinates: { lat: -8.3405, lng: 115.092 }
  },
  {
    id: "barcelona",
    name: "Barcelona",
    country: "Spain",
    region: "Europe",
    imageTone: "architecture, beach, tapas",
    averageDailyCost: 190,
    idealDays: 5,
    bestMonths: ["Apr", "May", "Jun", "Sep", "Oct"],
    climate: "warm",
    tags: ["food", "culture", "beach", "nightlife", "art"],
    pace: "active",
    travelerTypes: ["couple", "solo", "friends", "family"],
    safety: 0.79,
    popularity: 0.9,
    coordinates: { lat: 41.3874, lng: 2.1686 }
  }
];

module.exports = { destinations };
